version: '3.9'

services:

  db:
    image: postgres:15.2
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    env_file:
      - ".env"
    ports:
      - "${BE_PORT}:${BE_PORT}"
    volumes:
      - "./backend:/backend"
    command: sh -c "alembic upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port ${BE_PORT}"
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file:
      - ".env"
    ports:
      - "${FE_PORT}:${FE_PORT}"
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
volumes:
  postgres_data:
