"""Create basic drink and ingredient models

Revision ID: 000fe1791dce
Revises: 0027d9a5b069
Create Date: 2023-06-22 15:16:05.140579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '000fe1791dce'
down_revision = '0027d9a5b069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('complicated', sa.Enum('EASY', 'MEDIUM', 'HARD', name='complicatedlevels'), nullable=False),
    sa.Column('drink_type', sa.Enum('ONE_SHOT', 'MULTIPLE_SHOT', 'DRINK', name='drinktypes'), nullable=False),
    sa.Column('preparation_description', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('with_alcohol', sa.Boolean(), nullable=True),
    sa.Column('is_possible_to_make', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinks_id'), 'drinks', ['id'], unique=False)
    op.create_index(op.f('ix_drinks_name'), 'drinks', ['name'], unique=True)
    op.create_table('ingredient_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredient_type', sa.Enum('LIQUID', 'BEER', 'FRUIT', 'VEGETABLE', 'SNACK', 'OTHER', name='ingredienttypes'), nullable=False),
    sa.Column('ingredient_unit', sa.Enum('MILLILITER', 'PIECE', 'PACK', name='ingredientunits'), nullable=False),
    sa.Column('storage_amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('with_alcohol', sa.Boolean(), nullable=True),
    sa.Column('can_be_ordered', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_storage_id'), 'ingredient_storage', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_storage_name'), 'ingredient_storage', ['name'], unique=True)
    op.create_table('ingredient_needed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('amount_needed', sa.Integer(), nullable=False),
    sa.Column('is_enough_to_make_a_drink', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_needed_id'), 'ingredient_needed', ['id'], unique=False)
    op.add_column('users', sa.Column('uuid', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('table', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('date_modified', sa.DateTime(), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.drop_column('users', 'id')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'date_modified')
    op.drop_column('users', 'date_creation')
    op.drop_column('users', 'table')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_column('users', 'uuid')
    op.drop_index(op.f('ix_ingredient_needed_id'), table_name='ingredient_needed')
    op.drop_table('ingredient_needed')
    op.drop_index(op.f('ix_ingredient_storage_name'), table_name='ingredient_storage')
    op.drop_index(op.f('ix_ingredient_storage_id'), table_name='ingredient_storage')
    op.drop_table('ingredient_storage')
    op.drop_index(op.f('ix_drinks_name'), table_name='drinks')
    op.drop_index(op.f('ix_drinks_id'), table_name='drinks')
    op.drop_table('drinks')
    # ### end Alembic commands ###
