"""added column for string image path

Revision ID: 782a388b1736
Revises: 319dc60754bb
Create Date: 2023-12-14 20:21:10.217648

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '782a388b1736'
down_revision = '319dc60754bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('ingredients_storage', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients_storage', 'image_path')
    op.drop_column('drinks', 'image_path')
    # ### end Alembic commands ###
