"""message

Revision ID: f8e883361874
Revises: 2c1b7656da7d
Create Date: 2024-09-30 19:55:28.811329

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8e883361874'
down_revision = '2c1b7656da7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drinks', 'with_alcohol',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('drinks', 'is_possible_to_make',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ingredients_needed', 'is_enough_to_make_a_drink',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ingredients_needed', 'ingredient_storage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingredients_storage', 'with_alcohol',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('ingredients_storage', 'can_be_ordered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients_storage', 'can_be_ordered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ingredients_storage', 'with_alcohol',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('ingredients_needed', 'ingredient_storage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingredients_needed', 'is_enough_to_make_a_drink',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('drinks', 'is_possible_to_make',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('drinks', 'with_alcohol',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
